version: '2'

services:

  influxdb:
    container_name: influxdb
    image: influxdb
    hostname: influxdb
    volumes:
      - "~/docker/influxdb/data:/var/lib/influxdb"
      - "~/docker/influxdb/etc:/etc/influxdb"
    ports:
      - "8086:8086"
      - "8083:8083"
      - "2003:2003"
